

export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS'
export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const SET_TYPE_PLUGIN_DATA = 'SET_TYPE_PLUGIN_DATA'
export const SET_ACTIVITY_PLUGIN_DATA = 'SET_ACTIVITY_PLUGIN_DATA'
